version: '3.3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: twine-timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-twine_solana_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      # Additional users will be created by init.sql
      GEYSER_USER: ${GEYSER_USER:-geyser_writer}
      GEYSER_PASSWORD: ${GEYSER_PASSWORD:-geyser_writer_password}
      # TimescaleDB specific settings
      TIMESCALEDB_TELEMETRY: "off"
    ports:
      - "127.0.0.1:5432:5432"  # Bind to localhost only
    volumes:
      # Database data
      - timescale_data:/var/lib/postgresql/data
      # Init scripts
      - ./schema/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      # Custom PostgreSQL configuration
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: >
      postgres
      -c shared_preload_libraries=timescaledb,pg_stat_statements
      -c config_file=/etc/postgresql/postgresql.conf
    shm_size: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twine_solana_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  timescale_data:
    driver: local

networks:
  default:
    name: twine-network
    driver: bridge