services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: twine-timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: twine_solana_db
      POSTGRES_USER: geyser_writer
      POSTGRES_PASSWORD: geyser_writer_password
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - twine-network
    shm_size: 1gb
    command: >
      postgres
      -c shared_preload_libraries=timescaledb,pg_stat_statements
      -c shared_buffers=4GB
      -c effective_cache_size=12GB
      -c work_mem=256MB
      -c maintenance_work_mem=1GB
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c wal_buffers=16MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=16
      -c max_parallel_workers_per_gather=8
      -c max_parallel_workers=16
      -c max_parallel_maintenance_workers=4
      -c checkpoint_completion_target=0.9
      -c wal_compression=on
      -c wal_log_hints=on
      -c wal_level=replica
      -c max_wal_senders=0
      -c synchronous_commit=off
      -c full_page_writes=on
      -c checkpoint_timeout=15min
      -c listen_addresses='*'
      -c max_connections=200
      -c superuser_reserved_connections=5
      -c timescaledb.max_background_workers=8
      -c log_line_prefix='%t [%p] %u@%d '
      -c log_checkpoints=on
      -c log_connections=on
      -c log_disconnections=on
      -c log_duration=off
      -c log_lock_waits=on
      -c log_statement=none
      -c log_timezone='UTC'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geyser_writer -d twine_solana_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    container_name: twine-prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=30d"
    ports:
      - "9090:9090"
    networks:
      - twine-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9090/-/healthy",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grafana-importer:
    image: alpine/curl
    container_name: twine-grafana-importer
    restart: on-failure
    depends_on:
      grafana:
        condition: service_healthy
    volumes:
      - ./scripts/import-library-panels.sh:/import-library-panels.sh:ro
      - ./config/grafana/provisioning/library_panels:/etc/grafana/provisioning/library_panels:ro
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:rw
    networks:
      - twine-network
    command: >
      sh -c "apk add --no-cache jq && sh /import-library-panels.sh"

  grafana:
    image: grafana/grafana:latest
    container_name: twine-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    networks:
      - twine-network
    depends_on:
      - prometheus
      - timescaledb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  timescale_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  twine-network:
    external: true
