services:
  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:9.0
    container_name: twine-pgadmin
    restart: unless-stopped
    user: "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@twinelabs.xyz
      PGADMIN_DEFAULT_PASSWORD: Twine202%202%
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./config/pgadmin/pgpass:/tmp/pgpass:ro
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - twine-network
    entrypoint: bash
    command: >
      -c "cp /tmp/pgpass /var/lib/pgadmin/pgpass && chmod 0600 /var/lib/pgadmin/pgpass && /entrypoint.sh"
    depends_on:
      - timescaledb

  # Grafana for monitoring
  grafana:
    image: grafana/grafana:11.2.1
    container_name: twine-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-clock-panel,marcusolsson-json-datasource
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_BASIC_ENABLED: "true"
      GF_SMTP_ENABLED: "false"
      GF_LOG_MODE: console
      GF_LOG_LEVEL: info
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - twine-network
    depends_on:
      prometheus:
        condition: service_started

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: twine-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - twine-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      timescaledb:
        condition: service_healthy

  # PostgreSQL exporter for Prometheus
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: twine-postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://geyser_writer:geyser_writer_password@timescaledb:5432/twine_solana_db?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - twine-network
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  pgadmin_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  twine-network:
    external: true
