global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'twine-solana-geyser'

scrape_configs:
  - job_name: 'twine-geyser-plugin'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          instance: 'geyser-plugin'
          component: 'twine'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'