global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Geyser plugin metrics
  - job_name: 'geyser-plugin'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (if using postgres-exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'twine-geyser'
    static_configs:
      # Try multiple approaches to reach the host
      - targets: ['host.docker.internal:9091']
        labels:
          instance: 'host-docker'
      - targets: ['172.17.0.1:9091']
        labels:
          instance: 'docker-bridge'
      # If running on the same network
      - targets: ['twine-geyser:9091']
        labels:
          instance: 'container-name'